"""Auto-generated migration

Revision ID: 53e192f49af2
Revises: 125ea59739c0
Create Date: 2025-05-19 17:05:18.639320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e192f49af2'
down_revision: Union[str, None] = '125ea59739c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datas2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data5', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datas2', schema=None) as batch_op:
        batch_op.drop_column('data5')

    # ### end Alembic commands ###
