"""Auto-generated migration

Revision ID: 5bf7a19f7083
Revises: c2799710e834
Create Date: 2025-06-11 15:02:47.142943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf7a19f7083'
down_revision: Union[str, None] = 'c2799710e834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('test1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('qdata', sa.REAL(), nullable=True),
    sa.Column('idata', sa.REAL(), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('qdata', sa.REAL(), nullable=True),
    sa.Column('idata', sa.REAL(), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('changedata', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
