"""init

Revision ID: 74de9dfda460
Revises: 94621cedcbb7
Create Date: 2025-05-16 14:06:06.763615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74de9dfda460'
down_revision: Union[str, None] = '94621cedcbb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datas2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data3', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datas2', schema=None) as batch_op:
        batch_op.drop_column('data3')

    # ### end Alembic commands ###
