"""init

Revision ID: 94621cedcbb7
Revises: 2ce9310db41e
Create Date: 2025-05-16 12:27:27.498130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94621cedcbb7'
down_revision: Union[str, None] = '2ce9310db41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datas2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data2', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datas2', schema=None) as batch_op:
        batch_op.drop_column('data2')

    # ### end Alembic commands ###
