"""Auto-generated migration

Revision ID: c2799710e834
Revises: f623ebea6ca1
Create Date: 2025-05-26 16:14:05.068893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2799710e834'
down_revision: Union[str, None] = 'f623ebea6ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datas2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Integer(), nullable=True),
    sa.Column('data2', sa.Integer(), nullable=True),
    sa.Column('data3', sa.Integer(), nullable=True),
    sa.Column('data4', sa.Integer(), nullable=True),
    sa.Column('data5', sa.Integer(), nullable=True),
    sa.Column('data6', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qdata', sa.REAL(), nullable=True),
    sa.Column('idata', sa.REAL(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('changedata', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qdata', sa.REAL(), nullable=True),
    sa.Column('idata', sa.REAL(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test1')
    op.drop_table('test')
    op.drop_table('datas2')
    op.drop_table('datas')
    # ### end Alembic commands ###
