"""Auto-generated migration

Revision ID: df20c8972716
Revises: 74de9dfda460
Create Date: 2025-05-19 16:49:18.542403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df20c8972716'
down_revision: Union[str, None] = '74de9dfda460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datas2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data4', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datas2', schema=None) as batch_op:
        batch_op.drop_column('data4')

    # ### end Alembic commands ###
