"""Auto-generated migration

Revision ID: f623ebea6ca1
Revises: b2401e83c521
Create Date: 2025-05-26 16:01:10.742222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f623ebea6ca1'
down_revision: Union[str, None] = 'b2401e83c521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datas')
    op.drop_table('datas2')
    op.drop_table('test1')
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('qdata', sa.REAL(), nullable=True),
    sa.Column('idata', sa.REAL(), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.Column('changedata', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('qdata', sa.REAL(), nullable=True),
    sa.Column('idata', sa.REAL(), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datas2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.INTEGER(), nullable=True),
    sa.Column('data2', sa.INTEGER(), nullable=True),
    sa.Column('data3', sa.INTEGER(), nullable=True),
    sa.Column('data4', sa.INTEGER(), nullable=True),
    sa.Column('data5', sa.INTEGER(), nullable=True),
    sa.Column('data6', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
