"""Auto-generated migration

Revision ID: c281c2626b20
Revises: f2cad8346aad
Create Date: 2025-06-11 15:02:47.180089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c281c2626b20'
down_revision: Union[str, None] = 'f2cad8346aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test3')
    op.drop_table('test2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('qdata', sa.REAL(), nullable=True),
    sa.Column('idata', sa.REAL(), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test3',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('qdata', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
